export {default as Navbar} from './Navbar'
export {default as Home} from './Home'
export {default as HomeFooter} from './HomeFooter'
export {default as Contact} from './Contact'
export {default as Map} from './Map'
export {default as Service} from './Services'
export {default as MainApp} from './MainApp'
export {default as GetAFreeQuote} from './GetAFreeQuoteComponent'